### PR TITLE
Fix: now able to set unicode bodies

### PR DESCRIPTION
**Pull request by alexeyknyshev**
Example yaml, body contatins russian utf8 symbols:

- test:
    - name: "User login contains invalid chars"
    - group: "UserCreate"
    - url: "/user"
    - method: "POST"
    - headers: { Content-type: "application/json", Id: 4 }
    - body: '{"login":"user_петя","password":"pwd2"}'
    - expected_status: 400

### CODE REVIEW

**Comment by svanoort** [comment]
@alexeyknyshev Thank you for your contribution!   There are a couple questions to consider for the Unicode handling here, which need to be addressed before modifying it:

How will this handle cases where already-encoded or non-UTF8 content is supplied by the  [contenthandler](https://github.com/svanoort/pyresttest/blob/master/pyresttest/contenthandling.py)?  

What about cases where a user may not wish to submit Unicode-encoded content?  For example, suppose they only take ASCII inputs to a legacy API, or use a custom encoding (rare, but possible).

How does this test that encoding is handled correctly?  Does it cover the 4 different ways that you can submit body content?  (Inline string in YAML, templated string, read from file, read from file and apply templating, and I'm ignoring applying templating to file paths here). 

I should mention that more thorough validation of Unicode content is a high priority for this project in the next few releases, since it goes hand in hand with parsing refactors and hasn't got enough test coverage.  I've opened https://github.com/svanoort/pyresttest/issues/104 to make that requirement explicit.  So, if you're able to revise this PR to reflect these questions, it will be a very useful contribution indeed!

**Comment by alexeyknyshev** [comment]
Hi, man!
Sorry for the long reply. I have not tested anything except inline bodies. While playing around pyresttest I have found that Russian UTF8 symbols crashes pyresttest.

In my opinion there's no problem with <b>encode('unicode_escape')</b> due to it will encode only non-ascii chars anyway. And it happens just after any body processing, such as templated strings and so on.

Regards, Alexey Knyshev

**Comment by svanoort** [comment]
@alexeyknyshev I have added functional tests for Unicode handling to my working branch for parsing fixes:  https://github.com/svanoort/pyresttest/tree/feature-refactor-parsing - this also has the starting point for a safer encoding handler (and support for using templating with Unicode content).

> In my opinion there's no problem with encode('unicode_escape') due to it will encode only non-ascii chars anyway.

This is why correct encoding handling is tricky: there are lots of ways to make mistakes in subtle ways. 
In this case, what if your content contains escape sequences?  

For example:
```python
>>> '\\u6307'.encode('unicode_escape')
# Returns
'\\\\u6307'
```
Your output will differ from your input, and if your input is already encoded or intended to be raw binary, the output will now be incorrect.  Make sense?

To safely handle Unicode, it is necessary to do conversion only when you're finally passing content to curl, checking to see if it's Unicode and converting if needed (setting an appropriate HTTP header for encoding).  I did this wrong in the initial implementation, and now am having to go back and fix this and all the poor encoding handling decisions made at the beginning (especially along with Unicode/byte changes for Python 3 compatibility).

If you want to take a crack at handling this in a safe fashion, I'd certainly welcome a PR based off branch feature-refactor-parsing, which already has tests and helper functions for safe encoding.

**Comment by svanoort** [comment]
Closing this PR for now, since it doesn't meet PR merge criteria per https://github.com/svanoort/pyresttest#feedback and does not address critical cases.

Clear requirements for this have been now been laid out, including test code and initial helper functions in the [feature-refactor-parsing branch](https://github.com/svanoort/pyresttest/tree/feature-refactor-parsing).

**Pull request closed without merging**
